apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: js-kube-client
  name: js-kube-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: js-kube-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: js-kube-client
    spec:
      containers:
        - image: gh3s/js-kube-client:v0.0.52
          name: js-kube-client
          resources: {}
          ports:
            - containerPort: 8080

