apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: js-kube-api
  name: js-kube-api
  namespace: metallb-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30651
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: js-kube-api
  sessionAffinity: None
  type: LoadBalancer